baseURL: https://gophergo.dev/
languageCode: en-us
title: Gopher Go!
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: monokai
    tabWidth: 2

theme: PaperMod
params:
  showToc: true
  showBreadCrumbs: true
  showCodeCopyButtons: true

  assets:
    disableHLJS: true

    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"

  showPostNavLinks: true
  profileMode:
    enabled: true
    buttons:
      - name: Basics
        url: "/basics"
      - name: Standard Library
        url: "/std"
      - name: Resources
        url: "/resources"
      - name: Projects
        url: "/projects"
      - name: Go Toolchain
        url: "/cmd"
